server {
    listen 80;
    server_name localhost;

    # 1. Racine par défaut pour le Frontend (SPA)
    root /var/www/frontend;
    index index.html;

    # Gestion des routes du Frontend (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        root /var/www/backend/public;
        try_files $uri /index.php$is_args$args;
    }

    # Traitement des scripts PHP ( pour Symfony)
    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME /var/www/backend/public/index.php;
        fastcgi_param DOCUMENT_ROOT /var/www/backend/public;

        internal;
    }

    # Sécurité : Interdire l'accès direct à d'autres fichiers .php
    location ~ \.php$ {
        return 404;
    }

    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
